# glcoind configuration
# some values might be overruled directly systemd-service exec call parameters

# mainnet/testnet
testnet=0

# Glcoind options
server=1
daemon=1
txindex=0
disablewallet=1
peerbloomfilters=1
datadir=/mnt/hdd/app-storage/glcoin
main.debuglogfile=/mnt/hdd/app-data/glcoin/debug.log
test.debuglogfile=/mnt/hdd/app-data/glcoin/testnet3/debug.log
signet.debuglogfile=/mnt/hdd/app-data/glcoin/signet/debug.log

# Connection settings
rpcuser=raspibolt
rpcpassword=passwordB
main.rpcport=1617
test.rpcport=11617
rpcallowip=127.0.0.1
main.rpcbind=127.0.0.1:1617
test.rpcbind=127.0.0.1:11617
main.zmqpubrawblock=tcp://127.0.0.1:21617
main.zmqpubrawtx=tcp://127.0.0.1:21618

# Raspberry Pi optimizations
dbcache=128
maxorphantx=10
maxmempool=300
maxconnections=40
maxuploadtarget=5000

# clearnet by default — switch to Tor via: tor.network.sh on
onlynet=ipv4
onlynet=ipv6

# bootstrap peers
main.addnode=glcoin.org:1618
signet.addnode=seed.glcoin.org:31618
