{
 "title": "Glcoin/LN/electrs - Node",
 "time": { "from": "now-4d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"ln_info\" WITH KEY=host"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Summary - Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "system",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "glcoind - service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_service",
     "groupBy": [
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "service_uptime",
     "query": "SELECT last(\"uptime\") FROM \"service_uptime\" WHERE (\"host\" =~ /^$host$/ AND \"service\" = 'glcoind') AND $timeFilter GROUP BY \"service\"",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "glcoind" }
     ]
    }
   ]
  },
  {
   "title": "lnd - service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_service",
     "groupBy": [
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "service_uptime",
     "query": "SELECT last(\"uptime\") FROM \"service_uptime\" WHERE (\"host\" =~ /^$host$/ AND \"service\" = 'lnd') AND $timeFilter GROUP BY \"service\"",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "lnd" }
     ]
    }
   ]
  },
  {
   "title": "electrs - service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_service",
     "groupBy": [
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "service_uptime",
     "query": "SELECT last(\"uptime\") FROM \"service_uptime\" WHERE (\"host\" =~ /^$host$/ AND \"service\" = 'electrs') AND $timeFilter GROUP BY \"service\"",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "electrs" }
     ]
    }
   ]
  },
  {
   "title": "Glcoin - Recv",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glcoin_nettotals",
     "query": "SELECT last(\"totalbytesrecv\") AS \"Recv\" FROM \"glcoin_nettotals\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "totalbytesrecv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Recv" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Glcoin - Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glcoin_nettotals",
     "query": "SELECT last(\"totalbytessent\") AS \"Sent\" FROM \"glcoin_nettotals\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "totalbytessent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Blockchain Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glcoin_blockchaininfo",
     "query": "SELECT last(\"size_on_disk\") FROM \"glcoin_blockchaininfo\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "size_on_disk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Glcoin peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glcoin_connectioncount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "LN peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ln_info",
     "query": "SELECT last(\"num_peers\") FROM \"ln-info\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_peers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Quick Summary - IP Addresses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IPv4 (global)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ipaddr",
     "groupBy": [
      { "params": [ "ipaddr" ], "type": "tag" }
     ],
     "measurement": "ipinfo",
     "query": "SELECT last(\"value\") FROM \"glcoin-uptime\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "IPv4" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ipaddr",
     "groupBy": [
      { "params": [ "ipaddr" ], "type": "tag" }
     ],
     "measurement": "ipinfo",
     "query": "SELECT last(\"value\") FROM \"glcoin-uptime\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "IPv4" }
     ]
    }
   ]
  },
  {
   "title": "glcoind",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ipaddr",
     "groupBy": [
      { "params": [ "ipaddr" ], "type": "tag" }
     ],
     "measurement": "ipinfo",
     "query": "SELECT last(\"value\") FROM \"glcoin-uptime\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "glcoind" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ipaddr",
     "groupBy": [
      { "params": [ "ipaddr" ], "type": "tag" }
     ],
     "measurement": "ipinfo",
     "query": "SELECT last(\"value\") FROM \"glcoin-uptime\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "glcoind" }
     ]
    }
   ]
  },
  {
   "title": "public IPv4",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ipaddr",
     "groupBy": [
      { "params": [ "ipaddr" ], "type": "tag" }
     ],
     "measurement": "ipinfo",
     "query": "SELECT last(\"uptime\") FROM \"raspiblesk_ip_info\" WHERE (\"host\" =~ /^$host$/ AND \"origin\" = 'publicIP') AND $timeFilter GROUP BY \"ipaddr\"",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "publicIP" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ipaddr",
     "groupBy": [
      { "params": [ "ipaddr" ], "type": "tag" }
     ],
     "measurement": "ipinfo",
     "query": "SELECT last(\"value\") FROM \"glcoin-uptime\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "publicIP" }
     ]
    }
   ]
  },
  {
   "title": "lnd",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ipaddr",
     "groupBy": [
      { "params": [ "ipaddr" ], "type": "tag" }
     ],
     "measurement": "ipinfo",
     "query": "SELECT last(\"value\") FROM \"glcoin-uptime\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "lnd" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ipaddr",
     "groupBy": [
      { "params": [ "ipaddr" ], "type": "tag" }
     ],
     "measurement": "ipinfo",
     "query": "SELECT last(\"value\") FROM \"glcoin-uptime\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "lnd" }
     ]
    }
   ]
  },
  {
   "title": "Quick Summary - Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Glcoin Blocks (Web)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "web_glcoin_info",
     "query": "SELECT last(\"blocks\") FROM \"glcoin-blockchaininfo\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "n_blocks_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Glcoin Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "glcoin_blockchaininfo",
     "query": "SELECT last(\"blocks\") FROM \"glcoin-blockchaininfo\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "blocks" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "LN BlockHeight",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "ln_info",
     "query": "SELECT last(\"blocks\") FROM \"glcoin-blockchaininfo\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "block_height" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "electrs IndexHeight",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "electrs_info",
     "query": "SELECT last(\"blocks\") FROM \"glcoin-blockchaininfo\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "index_height" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Beat / 24h (Web)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Block Beat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "web_glcoin_info",
     "select": [
      [
       { "params": [ "n_blocks_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Beat / 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Block Beat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glcoin_blockchaininfo",
     "select": [
      [
       { "params": [ "blocks" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Quick Summary - MemPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pending Tx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrs_info",
     "select": [
      [
       { "params": [ "mempool_txs_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "< 1 gsat/vbyte",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_fee_rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fee_rate" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrs_info",
     "select": [
      [
       { "params": [ "mempool_txs_vsize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "fee_rate",
       "operator": "=",
       "value": "[                   0,                    1)"
      }
     ]
    }
   ]
  },
  {
   "title": "< 2 gsat/vbyte",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_fee_rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrs_info",
     "select": [
      [
       { "params": [ "mempool_txs_vsize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "fee_rate",
       "operator": "=",
       "value": "[                   2,                    4)"
      },
      {
       "condition": "OR",
       "key": "fee_rate",
       "operator": "=",
       "value": "[                   0,                    1)"
      }
     ]
    }
   ]
  },
  {
   "title": "fees",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 26 },
   "targets": [
    {
     "alias": "$tag_fee_rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fee_rate" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrs_info",
     "query": "SELECT \"electrs_mempool_vsize\"  / __series.field FROM \"autogen\".\"prometheus\" WHERE $timeFilter GROUP BY \"fee_rate\"",
     "select": [
      [
       { "params": [ "mempool_txs_vsize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mempool_txs_vsize", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "api.blockchain.info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Glcoin Blocks (Web)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "web_glcoin_info",
     "query": "SELECT last(\"blocks\") FROM \"glcoin-blockchaininfo\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "n_blocks_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Beat / 24h (Web)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Block Beat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "web_glcoin_info",
     "select": [
      [
       { "params": [ "n_blocks_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocks Mined / 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Blocks mined",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "web_glcoin_info",
     "select": [
      [
       { "params": [ "n_blocks_mined" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Fees / 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Fees per 24h",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "web_glcoin_info",
     "select": [
      [
       { "params": [ "total_fees_btc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Marketprice USD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Marketprice USD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "web_glcoin_info",
     "select": [
      [
       { "params": [ "market_price_usd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime & Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime system / services",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "alias": "system",
     "limit": "1",
     "measurement": "system",
     "query": "SELECT last(\"uptime\") FROM \"autogen\".\"system\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_service",
     "groupBy": [
      { "params": [ "service" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "service_uptime",
     "query": "SELECT last(\"uptime\") FROM \"autogen\".\"service-uptime\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"service\" LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Glcoin - totals",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "limit": "1",
     "measurement": "glcoin_nettotals",
     "query": "SELECT last(\"totalbytesrecv\") AS \"Bytes recv\" FROM \"autogen\".\"glcoin-nettotals\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"host\" LIMIT 1",
     "select": [
      [
       { "params": [ "totalbytesrecv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes recv" ], "type": "alias" }
      ],
      [
       { "params": [ "totalbytessent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "limit": "1",
     "measurement": "glcoin_blockchaininfo",
     "select": [
      [
       { "params": [ "size_on_disk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Size on disk" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "IP Address History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "alias": "$tag_origin = $tag_ipaddr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "origin" ], "type": "tag" },
      { "params": [ "ipaddr" ], "type": "tag" }
     ],
     "measurement": "ipinfo",
     "select": [
      [
       { "params": [ "created" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "IP addresses from services and network devices",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "alias": "$tag_origin = $tag_ipaddr",
     "groupBy": [
      { "params": [ "ipaddr" ], "type": "tag" },
      { "params": [ "origin" ], "type": "tag" }
     ],
     "measurement": "ipinfo",
     "query": "SELECT last(\"uptime\") FROM \"autogen\".\"system\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "IP Address changes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_origin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "origin" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipinfo",
     "select": [
      [
       { "params": [ "changed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Services Start History",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "dateTimeFromNow" }
   ],
   "targets": [
    {
     "alias": "$tag_systemd_unit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "systemd_unit" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "query": "SELECT last(\"created_at\")  / 1000000 FROM \"procstat\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"systemd_unit\"",
     "select": [
      [
       { "params": [ "created_at" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Peers / Connection Count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Glcoin peers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glcoin_connectioncount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "LN peers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ln_info",
     "select": [
      [
       { "params": [ "num_peers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Blockchain Info & MemPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Beat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "alias": "Block Beat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glcoin_blockchaininfo",
     "select": [
      [
       { "params": [ "blocks" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Blockchain Info",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Glcoin - Blocks",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glcoin_blockchaininfo",
     "select": [
      [
       { "params": [ "blocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Glcoin - Headers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glcoin_blockchaininfo",
     "select": [
      [
       { "params": [ "headers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Glcoin - Verification Progress",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glcoin_blockchaininfo",
     "select": [
      [
       { "params": [ "verificationprogress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "LN - Bockheight",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ln_info",
     "select": [
      [
       { "params": [ "block_height" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "electrs - Indexheight",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrs_info",
     "select": [
      [
       { "params": [ "electrs_index_height" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Pending Tx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Pending Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrs_info",
     "select": [
      [
       { "params": [ "mempool_txs_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "fees via mempool size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_fee_rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fee_rate" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrs_info",
     "query": "SELECT last(\"mempool_txs_vsize\") FROM \"autogen\".\"electrs_info\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"fee_rate\" fill(null)",
     "select": [
      [
       { "params": [ "mempool_txs_vsize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mempool_txs_vsize", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Computer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Temperature / Frequence",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "celsius", "label": "CPU Temperature" }
   ],
   "targets": [
    {
     "alias": "CPU Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "CPU Frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_frequency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "20" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU user/system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") AS \"user\", mean(\"usage_system\")AS \"system\" FROM \"autogen\".\"cpu\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "CPU system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") AS \"user\", mean(\"usage_system\")AS \"system\" FROM \"autogen\".\"cpu\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "CPU idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") AS \"user\", mean(\"usage_system\")AS \"system\" FROM \"autogen\".\"cpu\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "CPU io wait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") AS \"user\", mean(\"usage_system\")AS \"system\" FROM \"autogen\".\"cpu\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "SystemLoad / FreeMem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "15min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"load1\") AS \"load 1min\", mean(\"load5\") AS \"load 5min\", mean(\"load15\") AS \"load 15min\" FROM \"system\" WHERE $timeFilter GROUP BY time(1m), \"host\"\n",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avail mem" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Mem & Swap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Swap used %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Mem used %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Mem avail %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk used %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"usage_user\") AS \"user\", mean(\"usage_system\")AS \"system\" FROM \"autogen\".\"cpu\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk free space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"usage_user\") AS \"user\", mean(\"usage_system\")AS \"system\" FROM \"autogen\".\"cpu\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}