name: arm64-rpi-lean-image

concurrency:
  group: arm64-rpi-lean-image-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: ['dev']
    paths:
      - 'build_sdcard.sh'
      - 'home.admin/config.scripts/**'
      - 'ci/arm64-rpi/**'
  pull_request:
    branches: ['dev']
    paths:
      - 'build_sdcard.sh'
      - 'home.admin/config.scripts/**'
      - 'ci/arm64-rpi/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set build values
        id: set_values
        run: |
          echo "BUILD_VERSION=$(git describe --always --tags)" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
          echo "GITHUB_USER=${{ github.event.pull_request.head.repo.owner.login || github.repository_owner }}" >> $GITHUB_ENV

      - name: Show build info
        run: |
          echo "Building Raspiblésk Lean Image"
          echo "Version: ${{ env.BUILD_VERSION }}"
          echo "Branch:  ${{ env.BRANCH_NAME }}"

      - name: Run build script (Lean)
        run: |
          cd ci/arm64-rpi
          bash packer.build.arm64-rpi.sh \
            --pack lean \
            --github_user ${{ env.GITHUB_USER }} \
            --branch ${{ env.BRANCH_NAME }} \
            --image_size 18G

      - name: Calculate SHA256 checksum
        run: |
          cd ci/arm64-rpi
          sha256sum raspiblesk-arm64-rpi-lean.img > raspiblesk-arm64-rpi-lean.img.sha256

      - name: Upload lean image + checksum
        uses: actions/upload-artifact@v4
        with:
          name: raspiblesk-arm64-rpi-lean-image-${{ env.BUILD_VERSION }}
          path: |
            ci/arm64-rpi/raspiblesk-arm64-rpi-lean.img
            ci/arm64-rpi/raspiblesk-arm64-rpi-lean.img.sha256
          retention-days: 30
